version: '3.1'
services:
  web:
    image: odoo-14
    depends_on:
      - db
    ports:
      - "8064:8069"
    volumes:
      - ./etc/odoo:/etc/odoo/
      - ./log/odoo:/var/odoo
      - ./addons:/mnt/addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
