version: '3.1'
services:
  web:
    image: odoo-15
    depends_on:
      - db
    ports:
      - "8064:8069"
    volumes:
      - ./addons/oca:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
