from . import account_move
from . import account_payment_register
from . import eg_ecom_instance
from . import eg_product_template
from . import eg_sync_history
from . import product_template
from . import res_config_settings
from . import res_partner
from . import sale_order
