version: '3'
services:
    dolidb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpwd
            MYSQL_DATABASE: dolibarr
    doliweb:
        image: dolibarr-17
        environment:
            HOST_USER_ID: $HOST_USER_ID
        volumes:
            - ./dolibarr-15.0.3/htdocs:/var/www/html/
            - ./documents:/var/documents
        ports:
            - "8070:80"
        depends_on:
            - dolidb
