version: '3.1'
services:
  web:
    image: odoo-16-lefilament
    depends_on:
      - db
    ports:
      - "8164:8069"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
